### ISSUE TITLE
어뷰즈라고 인식 되지 않도록 영어 안내문 추가

### ISSUE THREAD

**Issue by iz4blue** [imyaman/kkeun-ma-rit-gi#7]
어뷰징이라고 오해할 수 있는 형태의 연습이라고 생각됩니다.

혹시라도 신고나 적발(?) 되더라도 pull request 와 accept 에 대해서 연습하기 위해서 운영된다.
이렇게 영어로 안내가 적혀 있으면 좋을 것 같습니다.

추가로 다음의 내용도 있었으면 합니다.
- pull request 와 accept 에 대해서 연습하기 위해서 운영됨
- contributer 가 추가 되는 이유는 accept 에 대한 연습을 위한 것이다.

이걸 영작 해주셔서 README.md 에 추가해주시면 좋을 것 같습니다.
전 영어가 짧아소...

**Comment by imyaman** [comment]
@imyagirl 님께 영작 부탁해 보겠습니다.
